;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        cider-load-buffer
        cljr-slash
        swiper
        ))

(setq mc/cmds-to-run-once
      '(
        backward-sexp
        comint-previous-input
        crux-move-beginning-of-line
        end-of-buffer
        forward-sexp
        iedit-switch-to-mc-mode
        ivy-end-of-buffer
        sql-magic-go
        sql-magic-semicolon
        ))
