;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        ))

(setq mc/cmds-to-run-once
      '(
        comint-previous-input
        end-of-buffer
        iedit-switch-to-mc-mode
        ivy-end-of-buffer
        ))
